1 = a
2 = b
3 = c
4 = d
5 = e
6 = f
7 = g
8 = h
9 = i
a = j
b = k
c = l
d = m
e = n
f = o
10 = p
11 = q
12 = r
13 = s
14 = t
15 = u
16 = v
17 = w
18 = x
19 = y
1a = z
1b = 1
1c = 2
1d = 3
1e = 4
1f = 5
20 = 6
21 = 7
22 = 8
23 = 9
24 = 0
25 = ent
26 = esc
27 = backspace
28 = tab
29 = space
2a = +?
2b = \
2c = å
2d = ^
2f = '*
30 = ø
31 = æ
32 = |
33 = ,
34 = .
35 = -
36 = caps
37 = f1
38 = f2
39 = f3
3a = f4
3b = f5
3c = f6
3d = f7
3e = f8
3f = f9
40 = f10
41 = f11
42 = f12
43 = prnt
44 = lock
45 = p/b
46 = ins
47 = home
48 = pgup
49 = del
4a = end
4b = pgd
4c = right
4d = left
4e = down
4f = up
50 = numlck
51 = n/
52 = n*
53 = n-
54 = n+
55 = nent
56 = n1
57 = n2
58 = n3
59 = n4
5a = n5
5b = n6
5c = n7
5d = n8
5e = n9
5f = n0
60 = n,
61 = <
62 = context
68 = ctrl
69 = shift
6a = alt
6b = win
6c = lctrl
6d = rshift
6e = altgr
6f = fn
99 = light
9b = play
9c = mute
9d = forward
9e = back
b4 = g1
b5 = g2
b6 = g3
b7 = g4
b8 = g5
b9 = g6
ba = g7
bb = g8
bc = g9
d2 = logo
